--触发条件数据
allachiv_eventdata={
["intogame"] = nil,
["firsteat"] = nil,
["supereat"] = 100,
["danding"] = 10,
["messiah"] = 5,
["walkalot"] = 60*300,
["stopalot"] = 60*90,
["tooyoung"] = nil,
["evil"] = 3,
["snake"] = 10,
["deathalot"] = 10,
["nosanity"] = 600,
["sick"] = nil,
["coldblood"] = nil,
["burn"] = nil,
["freeze"] = nil,
["goodman"] = 30,
["brother"] = 30,
["fishmaster"] = 60,
["pickmaster"] = 1500,
["chopmaster"] = 700,
["cookmaster"] = 200,
["buildmaster"] = 800,
["longage"] = 70,
["noob"] = nil,
["luck"] = nil,
["black"] = nil,
["tank"] = 3000,
["angry"] = 100000,
["icebody"] = 600,
["firebody"] = 600,
["moistbody"] = 600,
["rigid"] = nil,
["ancient"] = nil,
["queen"] = nil,
["king"] = nil,
["all"] = nil,
["minotaur"] = nil,
["sand"] = nil,

["pickappren"] = 750,
["chopappren"] = 400,
["mineappren"] = 200,
["minemaster"] = 350,
["cookappren"] = 100,
["buildappren"] = 400,
["santa"] = nil,
["knight"] = nil,
["bishop"] = nil,
["rook"] = nil,
["starve"] = 600,
["catperson"] = 15,
["rose"] = nil,
["butcher"] = 20,
["goatperd"] = 25,
["mossling"] = 10,
["weetusk"] = 3,
["secondchance"] = nil,
["nature"] = 200,
["trader"] = 20,
["fuzzy"] = 5,
["hutch"] = nil,
["hentai"] = 10,
["alldiet"] = 40,
["spooder"] = 100,
["sleep"] = nil,

["pet"] = nil,
["birdclop"] = nil,
["caveage"] = 60*90,
["eathot"] = 10,
["eatcold"] = 10,
["rot"] = nil,
["knowledge"] = nil,
["dance"] = 100,
["oldage"] = 150,
["superstar"] = 100,
["rocklob"] = 10,
["teleport"] = 25,
["horror"] = 3, --Spooder/Hound/Pengull

["antdeath"] = nil, --Sinkhole/Cave-In
["malb"] = nil,
["revenge"] = nil,
["pacifist"] = 60*40,
["beefalo"] = nil,
["kite"] = 10000,
}

--奖励获得数值
allachiv_coindata={
["hungerup"] = 1,
["sanityup"] = 1,
["healthup"] = 1,
["hungerrateup"] = TUNING.WILSON_HUNGER_RATE*.02,
["healthregen"] = .2,
["sanityregen"] = .2,
["speedup"] = .05,
["damageup"] = .1,
["absorbup"] = .05,
["crit"] = 5,
}

--成就获得点数
allachiv_coinget={
["intogame"] = 10,
["firsteat"] = 1,
["supereat"] = 2,
["danding"] = 2,
["messiah"] = 3,
["walkalot"] = 3,
["stopalot"] = 2,
["tooyoung"] = 2,
["evil"] = 2,
["snake"] = 2,
["deathalot"] = 2,
["nosanity"] = 3,
["sick"] = 2,
["coldblood"] = 2,
["burn"] = 1,
["freeze"] = 1,
["goodman"] = 3,
["brother"] = 3,
["fishmaster"] = 3,
["pickmaster"] = 4,
["chopmaster"] = 4,
["cookmaster"] = 4,
["buildmaster"] = 3,
["longage"] = 5,
["noob"] = 1,
["luck"] = 12,
["black"] = 7,
["tank"] = 5,
["angry"] = 5,
["icebody"] = 5,
["firebody"] = 5,
["moistbody"] = 5,
["rigid"] = 7,
["ancient"] = 7,
["queen"] = 7,
["king"] = 12,
["all"] = 3,
["minotaur"] = 7,
["sand"] = 5,
--162
["pickappren"] = 3,
["chopappren"] = 3,
["mineappren"] = 3,
["minemaster"] = 4,
["cookappren"] = 3,
["buildappren"] = 3,
["santa"] = 5,
["knight"] = 5,
["bishop"] = 6,
["rook"] = 5,
["starve"] = 5,
["catperson"] = 3,
["rose"] = 2,
["butcher"] = 5,
["goatperd"] = 5,
["mossling"] = 3,
["weetusk"] = 3,
["secondchance"] = 2,
["nature"] = 3,
["trader"] = 3,
["fuzzy"] = 3,
["hutch"] = 5,
["hentai"] = 5,
["alldiet"] = 8,
["spooder"] = 3,
["sleep"] = 1,
--99
["pet"] = 2,
["caveage"] = 3,
["birdclop"] = 3,
["eathot"] = 2,
["eatcold"] = 2,
["rot"] = 2,
["knowledge"] = 3,
["dance"] = 1,
["oldage"] = 3,
["superstar"] = 3,
["rocklob"] = 2,
["teleport"] = 2,
["horror"] = 3,

["antdeath"] = 2,
["malb"] = 5,
["revenge"] = 3,
["pacifist"] = 3,
["beefalo"] = 2,
["kite"] = 5,
--52
--Total 1st 312, 2nd 309, sum 621
}

--奖励消耗点数
allachiv_coinuse={
["hungerup"] = 1,
["sanityup"] = 1,
["healthup"] = 1,
["hungerrateup"] = 4,
["healthregen"] = 3,
["sanityregen"] = 3,
["speedup"] = 10,
["damageup"] = 15,
["absorbup"] = 30,
["crit"] = 25,
["fireflylight"] = 40,
["nomoist"] = 40,
["doubledrop"] = 35,
["goodman"] = 25,
["fishmaster"] = 25,
["pickmaster"] = 35,
["chopmaster"] = 35,
["cookmaster"] = 25,
["buildmaster"] = 60,
["refresh"] = 40,
["icebody"] = 50,
["firebody"] = 50,
["supply"] = 40,
["reader"] = 50,
["masterchef"] = 60,
["festive"] = 50,
["minemaster"] = 30,
["disguise"] = 30,
["nanobots"] = 45,
["fastworker"] = 30,
}

foodmenu = { "baconeggs", "butterflymuffin", "dragonpie", "fishtacos",
			 "fishsticks", "jammypreserves", "flowersalad", "frogglebunwich",
			 "fruitmedley", "guacamole", "honeyham", "honeynuggets",
			 "icecream", "jellybean", "kabobs", "mandrakesoup",
			 "meatballs", "bonestew", "watermelonicle", "monsterlasagna",
			 "perogies", "powcake", "pumpkincookie", "ratatouille",
			 "hotchili", "stuffedeggplant", "taffy", "trailmix",
			 "turkeydinner", "unagi", "waffles", "wetgoop",
			 "asparagussoup", "bananapop", "mashedpotatoes", "potatotornado",
			 "salsa", "pepperpopper", "vegstinger", "ceviche"
}

horrorprefabs = { "mutated_penguin", "mutatedhound", "spider_moon"}

PlayerNameList = {}

modversion = "3.0.4"